const courseData = {
  bitcoin: {
    title: 'Curso de Bitcoin',
    modules: [
      { title: '1. ¿Qué es Bitcoin?', path: '/aprende/bitcoin/que-es-bitcoin' },
      { title: '2. La Historia del Dinero', path: '/aprende/bitcoin/historia-del-dinero' },
      { title: '3. Blockchain y Criptografía', path: '/aprende/bitcoin/que-es-blockchain-y-criptografia' },
      { title: '4. ¿Cómo Funciona Bitcoin?', path: '/aprende/bitcoin/como-funciona-bitcoin' },
      { title: '5. Minería de Bitcoin', path: '/aprende/bitcoin/mineria-de-bitcoin' },
      { title: '6. Comprar y Vender Bitcoin', path: '/aprende/bitcoin/comprar-y-vender-bitcoin' },
      { title: '7. Wallets: Guarda tu Bitcoin', path: '/aprende/bitcoin/wallets-guarda-tu-bitcoin' },
      { title: '8. Seguridad y Buenas Prácticas', path: '/aprende/bitcoin/seguridad-y-buenas-practicas' },
      { title: '9. Bitcoin como Inversión', path: '/aprende/bitcoin/inversion' },
      { title: '10. La Red Lightning', path: '/aprende/bitcoin/lightning-network' },
      { title: '11. Mitos y Realidades', path: '/aprende/bitcoin/mitos-y-realidades' },
      { title: '12. El Futuro de Bitcoin', path: '/aprende/bitcoin/futuro-de-bitcoin' },
    ],
  },
  ethereum: {
    title: 'Curso de Ethereum',
    modules: [
      { title: '1. ¿Qué es Ethereum y Ether?', path: '/aprende/ethereum/que-es-ethereum' },
      { title: '2. Historia de Ethereum', path: '/aprende/ethereum/historia' },
      { title: '3. Bitcoin vs. Ethereum', path: '/aprende/ethereum/bitcoin-vs-ethereum' },
      { title: '4. La Máquina Virtual (EVM)', path: '/aprende/ethereum/la-maquina-virtual-evm' },
      { title: '5. Contratos Inteligentes', path: '/aprende/ethereum/contratos-inteligentes' },
      { title: '6. Gas: El Combustible de la Red', path: '/aprende/ethereum/gas-el-combustible-de-la-red' },
      { title: '7. Anatomía de una Transacción', path: '/aprende/ethereum/anatomia-de-una-transaccion' },
      { title: '8. Tokens ERC-20', path: '/aprende/ethereum/erc20' },
      { title: '9. DApps: Apps Descentralizadas', path: '/aprende/ethereum/dapps' },
      { title: '10. Finanzas Descentralizadas (DeFi)', path: '/aprende/ethereum/defi' },
      { title: '11. NFTs: Tokens No Fungibles', path: '/aprende/ethereum/nfts' },
      { title: '12. Escalabilidad y Capa 2', path: '/aprende/ethereum/capa-2' },
      { title: '13. Staking y Proof-of-Stake', path: '/aprende/ethereum/staking' },
      { title: '14. Ecosistema y Herramientas', path: '/aprende/ethereum/ecosistema' },
      { title: '15. El Futuro de Ethereum', path: '/aprende/ethereum/futuro' },
    ],
  },
  blockchains: {
    title: 'Curso de Blockchains',
    modules: [
      { title: '1. Introducción a Blockchain', path: '/aprende/blockchains/introduccion' },
      { title: '2. El Problema de los Generales Bizantinos', path: '/aprende/blockchains/el-problema-de-los-generales-bizantinos' },
      { title: '3. Criptografía Esencial', path: '/aprende/blockchains/criptografia-esencial' },
      { title: '4. Estructura de un Bloque', path: '/aprende/blockchains/estructura-de-un-bloque' },
      { title: '5. La Cadena: Inmutabilidad', path: '/aprende/blockchains/la-cadena-inmutabilidad' },
      { title: '6. Consenso: Proof-of-Work (PoW)', path: '/aprende/blockchains/consenso-proof-of-work' },
      { title: '7. Consenso: Proof-of-Stake (PoS)', path: '/aprende/blockchains/consenso-proof-of-stake' },
      { title: '8. Otros Mecanismos de Consenso', path: '/aprende/blockchains/otros-mecanismos-de-consenso' },
      { title: '9. Blockchains Públicas y Privadas', path: '/aprende/blockchains/blockchains-publicas-y-privadas' },
      { title: '10. Nodos y Redes P2P', path: '/aprende/blockchains/nodos-y-redes-p2p' },
      { title: '11. Forks: Blandos y Duros', path: '/aprende/blockchains/forks-blandos-y-duros' },
      { title: '12. Contratos Inteligentes', path: '/aprende/blockchains/contratos-inteligentes' },
      { title: '13. Oráculos Blockchain', path: '/aprende/blockchains/oraculos-blockchain' },
      { title: '14. Aplicación: Criptomonedas', path: '/aprende/blockchains/app-criptomonedas' },
      { title: '15. Aplicación: DeFi', path: '/aprende/blockchains/app-defi' },
      { title: '16. Aplicación: NFTs', path: '/aprende/blockchains/app-nfts' },
      { title: '17. Aplicación: Cadena de Suministro', path: '/aprende/blockchains/app-supply-chain' },
      { title: '18. El Trilema de la Blockchain', path: '/aprende/blockchains/trilema' },
      { title: '19. Interoperabilidad', path: '/aprende/blockchains/interoperabilidad' },
      { title: '20. Futuro y Desafíos', path: '/aprende/blockchains/futuro' },
    ],
  },
  trading: {
    title: 'Curso de Trading',
    modules: [
        { title: '1. Introducción al Trading', path: '/aprende/trading/introduccion' },
        { title: '2. Mercados: CEX vs. DEX', path: '/aprende/trading/mercados' },
        { title: '3. Tipos de Órdenes', path: '/aprende/trading/ordenes' },
        { title: '4. Conceptos Clave: Pares, Volumen', path: '/aprende/trading/conceptos' },
        { title: '5. Análisis Técnico: Gráficos', path: '/aprende/trading/analisis-tecnico' },
        { title: '6. Velas Japonesas', path: '/aprende/trading/velas-japonesas' },
        { title: '7. Soportes y Resistencias', path: '/aprende/trading/soportes-resistencias' },
        { title: '8. Líneas de Tendencia', path: '/aprende/trading/tendencias' },
        { title: '9. Indicadores: Medias Móviles', path: '/aprende/trading/medias-moviles' },
        { title: '10. Indicadores: RSI y MACD', path: '/aprende/trading/rsi-macd' },
        { title: '11. Patrones de Gráficos', path: '/aprende/trading/patrones' },
        { title: '12. Análisis Fundamental', path: '/aprende/trading/analisis-fundamental' },
        { title: '13. Tokenomics', path: '/aprende/trading/tokenomics' },
        { title: '14. Gestión de Riesgos', path: '/aprende/trading/gestion-de-riesgos' },
        { title: '15. Psicología del Trading', path: '/aprende/trading/psicologia-del-trading' },
        { title: '16. Estrategias: Scalping y Day Trading', path: '/aprende/trading/estrategias-scalping-day-trading' },
        { title: '17. Estrategias: Swing y Position Trading', path: '/aprende/trading/estrategias-swing-position-trading' },
        { title: '18. Trading con Apalancamiento', path: '/aprende/trading/trading-con-apalancamiento' },
        { title: '19. Herramientas del Trader', path: '/aprende/trading/herramientas' },
        { title: '20. On-Chain Analysis', path: '/aprende/trading/on-chain-analysis' },
        { title: '21. Airdrops y Farming', path: '/aprende/trading/airdrops-y-farming' },
        { title: '22. Creando un Plan de Trading', path: '/aprende/trading/creando-un-plan-de-trading' },
        { title: '23. Backtesting de Estrategias', path: '/aprende/trading/backtesting-de-estrategias' },
        { title: '24. Impuestos sobre Criptomonedas', path: '/aprende/trading/impuestos-sobre-cryptomonedas' },
        { title: '25. Errores Comunes a Evitar', path: '/aprende/trading/errores-comunes' },
    ],
  },
  nfts: {
    title: 'Curso de NFTs',
    modules: [
      { title: '1. ¿Qué es un NFT?', path: '/aprende/nfts/que-es-un-nft' },
      { title: '2. Historia de los NFTs', path: '/aprende/nfts/historia' },
      { title: '3. Estándares: ERC-721 vs. ERC-1155', path: '/aprende/nfts/estandares' },
      { title: '4. ¿Cómo Funciona la Propiedad Digital?', path: '/aprende/nfts/propiedad-digital' },
      { title: '5. Casos de Uso: Arte y Coleccionables', path: '/aprende/nfts/arte-y-coleccionables' },
      { title: '6. Casos de Uso: Gaming y Metaversos', path: '/aprende/nfts/gaming-metaversos' },
      { title: '7. Casos de Uso: Música, Entradas y más', path: '/aprende/nfts/musica-entradas-y-mas' },
      { title: '8. Cómo Crear (Mintear) un NFT', path: '/aprende/nfts/como-crear-un-nft' },
      { title: '9. Marketplaces de NFTs', path: '/aprende/nfts/marketplaces' },
      { title: '10. Analizando Proyectos de NFTs', path: '/aprende/nfts/analisis-de-proyectos' },
      { title: '11. Seguridad y Estafas Comunes', path: '/aprende/nfts/seguridad' },
      { title: '12. Aspectos Legales y Derechos', path: '/aprende/nfts/legal' },
      { title: '13. El Futuro de los NFTs', path: '/aprende/nfts/futuro' },
    ],
  },
  defi: {
    title: 'Curso de DeFi',
    modules: [
      { title: '1. ¿Qué es DeFi?', path: '/aprende/defi/que-es-defi' },
      { title: '2. Pilares de DeFi', path: '/aprende/defi/pilares' },
      { title: '3. Stablecoins: El Pilar de la Estabilidad', path: '/aprende/defi/stablecoins' },
      { title: '4. Préstamos Descentralizados', path: '/aprende/defi/prestamos' },
      { title: '5. Exchanges Descentralizados (DEXs)', path: '/aprende/defi/dex' },
      { title: '6. Liquidity Pools y AMMs', path: '/aprende/defi/liquidity-pools' },
      { title: '7. Yield Farming y Staking', path: '/aprende/defi/yield-farming' },
      { title: '8. Seguros Descentralizados', path: '/aprende/defi/seguros' },
      { title: '9. Oráculos en DeFi', path: '/aprende/defi/oraculos' },
      { title: '10. Gobernanza y Tokens DAO', path: '/aprende/defi/gobernanza' },
      { title: '11. DAOs: Organizaciones Autónomas', path: '/aprende/defi/daos' },
      { title: '12. Puentes (Bridges) entre Blockchains', path: '/aprende/defi/bridges' },
      { title: '13. Riesgos: Impermanent Loss', path: '/aprende/defi/impermanent-loss' },
      { title: '14. Riesgos: Hacks y Exploits', path: '/aprende/defi/hacks' },
      { title: '15. Herramientas y Dashboards', path: '/aprende/defi/herramientas' },
      { title: '16. Estrategias de Yield Farming', path: '/aprende/defi/estrategias-farming' },
      { title: '17. DeFi en Diferentes Redes', path: '/aprende/defi/multi-chain' },
      { title: '18. Derivados Sintéticos', path: '/aprende/defi/derivados' },
      { title: '19. Regulación y Futuro de DeFi', path: '/aprende/defi/regulacion' },
      { title: '20. Construyendo un Portfolio DeFi', path: '/aprende/defi/portfolio' },
    ],
  },
  wallets: {
    title: 'Curso de Wallets',
    modules: [
      { title: '1. ¿Qué es una Wallet?', path: '/aprende/wallets/que-es-una-wallet' },
      { title: '2. Claves Públicas y Privadas', path: '/aprende/wallets/claves' },
      { title: '3. Semilla de Recuperación (Seed Phrase)', path: '/aprende/wallets/seed-phrase' },
      { title: '4. Tipos de Wallets: Hot vs. Cold', path: '/aprende/wallets/hot-cold' },
      { title: '5. Wallets de Software', path: '/aprende/wallets/software' },
      { title: '6. Wallets de Hardware', path: '/aprende/wallets/hardware' },
      { title: '7. Wallets de Papel', path: '/aprende/wallets/papel' },
      { title: '8. Wallets de Custodia vs. No Custodia', path: '/aprende/wallets/custodia' },
      { title: '9. Cómo Elegir la Wallet Correcta', path: '/aprende/wallets/elegir' },
      { title: '10. Configurando tu Primera Wallet', path: '/aprende/wallets/configurar' },
      { title: '11. Enviando y Recibiendo Cripto', path: '/aprende/wallets/enviar-recibir' },
      { title: '12. Tarifas de Transacción (Gas)', path: '/aprende/wallets/tarifas' },
      { title: '13. Seguridad de la Wallet', path: '/aprende/wallets/seguridad' },
      { title: '14. Copias de Seguridad y Recuperación', path: '/aprende/wallets/backup-recuperacion' },
      { title: '15. Ataques Comunes a Wallets', path: '/aprende/wallets/ataques' },
      { title: '16. Wallets Multi-firma (Multi-sig)', path: '/aprende/wallets/multi-sig' },
      { title: '17. Integración con DApps y DeFi', path: '/aprende/wallets/dapps-defi' },
      { title: '18. El Futuro de las Wallets', path: '/aprende/wallets/futuro' },
    ],
  },
  seguridad: {
    title: 'Curso de Seguridad en Criptomonedas',
    modules: [
      { title: '1. Introducción a la Seguridad en Cripto', path: '/aprende/seguridad/introduccion' },
      { title: '2. Amenazas Comunes y Vectores de Ataque', path: '/aprende/seguridad/amenazas-comunes' },
      { title: '3. Protegiendo tus Wallets: Hot vs. Cold', path: '/aprende/seguridad/protegiendo-wallets' },
      { title: '4. Gestión de Claves Privadas y Semillas', path: '/aprende/seguridad/gestion-claves' },
      { title: '5. Autenticación de Dos Factores (2FA)', path: '/aprende/seguridad/autenticacion-dos-factores' },
      { title: '6. Phishing y Ataques de Ingeniería Social', path: '/aprende/seguridad/phishing-ingenieria-social' },
      { title: '7. Seguridad en Exchanges Centralizados (CEX)', path: '/aprende/seguridad/seguridad-cex' },
      { title: '8. Seguridad en Finanzas Descentralizadas (DeFi)', path: '/aprende/seguridad/seguridad-defi' },
      { title: '9. Identificando Estafas y Proyectos Maliciosos', path: '/aprende/seguridad/identificando-estafas' },
      { title: '10. Auditorías de Contratos Inteligentes', path: '/aprende/seguridad/auditorias-contratos' },
      { title: '11. Privacidad y Anonimato en Blockchain', path: '/aprende/seguridad/privacidad-anonimato' },
      { title: '12. Copias de Seguridad y Planes de Recuperación', path: '/aprende/seguridad/copias-seguridad-recuperacion' },
      { title: '13. Legislación y Cumplimiento Normativo', path: '/aprende/seguridad/legislacion-cumplimiento' },
      { title: '14. Reportando Incidentes de Seguridad', path: '/aprende/seguridad/reporte-incidentes' },
      { title: '15. El Futuro de la Seguridad en Cripto', path: '/aprende/seguridad/futuro-seguridad' },
    ],
  },
  // ...aquí se pueden añadir más cursos en el futuro
};

export const getCourseData = (slug) => {
  return courseData[slug] || null;
};

export default courseData;
